### ISSUE TITLE
Error tracing process: invalid literal for int() with base 0 ....

### ISSUE THREAD

**Issue by jlec** [p-e-w/maybe#7]
When running ```maybe foo.sh``` with ```foo.sh```

```bash
#!/bin/bash

rm -rvf ~/*
```

I get

```python
Error tracing process: invalid literal for int() with base 0: 'b"removed \'/home/justin/Test.png\'\\n"'.
WARNING:root:Terminate <PtraceProcess #2060>
WARNING:root:Terminate <PtraceProcess #2059>
```
This happens with

python-2.7/3.4
python-ptrace-0.8.1
blessings-1.6

**Comment by jlec** [comment]
Similar for ```maybe /bin/bash```which gives

```python
Error tracing process: invalid literal for int() with base 0: '"LS_COLORS=\'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.t'.
WARNING:root:Terminate <PtraceProcess #2723>
WARNING:root:Terminate <PtraceProcess #2722>
WARNING:root:Terminate <PtraceProcess #2721>
```

**Comment by sjakobi** [comment]
Same here, using https://github.com/commercialhaskell/stack:

```
~ $ sudo pip3 install maybe
[sudo] password for simon: 
The directory '/home/simon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/simon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting maybe
  Downloading maybe-0.2.1.tar.gz
Collecting blessings (from maybe)
  Downloading blessings-1.6.tar.gz
Collecting python-ptrace (from maybe)
  Downloading python-ptrace-0.8.1.tar.gz (93kB)
    100% |████████████████████████████████| 94kB 674kB/s 
Installing collected packages: blessings, python-ptrace, maybe
  Running setup.py install for blessings
  Running setup.py install for python-ptrace
  Running setup.py install for maybe
Successfully installed blessings-1.6 maybe-0.2.1 python-ptrace-0.8.1
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~ $ maybe stack path
Run from outside a project, using implicit global project config
Error tracing process: invalid literal for int() with base 0: 'b"Using resolver: lts-5.0 from implicit global project\'s config file: /home/simon/.stack/global-project/stack.yaml\\n"'.
WARNING:root:Terminate <PtraceProcess #10008>
```

**Comment by p-e-w** [comment]
Fixed in https://github.com/p-e-w/maybe/commit/7511ab9fb6bfdaa6704a3b63fd69d53d7674da56. Please update `maybe` to version 0.3.0.

**Comment by sjakobi** [comment]
Thanks, @p-e-w!

**Comment by develroo** [comment]
Hmmm

I'm afraid is seems this bug is back on Version: 0.4.0-4.

     maybe /usr/local/bin/update-calibre 
     Error tracing process: invalid literal for int() with base 0: 'AT_FDCWD'.

The script is very simple. 

     cat /usr/local/bin/update-calibre 
     
     #!/bin/bash
     wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
     exit 0


This is on Debian 9. 
Kernel 4.17.0-1-amd64 
Python 3.6.6
